In [5]:
import torch as th
from pprint import pp

from sympy.codegen.ast import float32, int64

# th.arange 函数能够创建一个张量
tensor_a = th.arange(12)
pp(tensor_a)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [12]:
tensor_a.shape # 注意没有括号，shape 是一个属性

torch.Size([12])

In [11]:
pp(tensor_a.size) # size 是一个方法，需要有括号
pp(tensor_a.size()) # size 方法

<built-in method size of Tensor object at 0x000002C4D21BFB10>
torch.Size([12])


In [14]:
tensor_a.numel() # 这个方法能够获取该张量的元素个数

12

In [17]:
tensor_a = tensor_a.reshape((3, 4)) # reshape 函数能够改变一个张量的形状
pp(tensor_a.shape)
pp(tensor_a)

torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [19]:
tensor_b = th.zeros(20) # 创建一个全 0 的张量
pp(tensor_b)
tensor_b = tensor_b.reshape((2, 2, -1))
pp(tensor_b)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [21]:
tensor_c = th.ones(20) # 全 1
tensor_c

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

In [22]:
tensor_d = th.rand((3, 4)) # 随机数
pp(tensor_d)

tensor([[0.2424, 0.4043, 0.7567, 0.1925],
        [0.7137, 0.6499, 0.4594, 0.6448],
        [0.7129, 0.9102, 0.2251, 0.6789]])


In [23]:
pp(tensor_d[0])

tensor([0.2424, 0.4043, 0.7567, 0.1925])


In [63]:
pp(tensor_d[:, 1])

tensor([0.4043, 0.6499, 0.9102])


In [34]:
tensor_e = th.rand((2, 2))
tensor_f = th.rand((2, 2))
pp(tensor_e)
pp(tensor_f)

tensor([[0.7825, 0.7980],
        [0.4721, 0.0813]])
tensor([[0.7861, 0.1394],
        [0.1013, 0.3593]])


In [36]:
tensor_e + tensor_f, tensor_e - tensor_f, tensor_e * tensor_f, tensor_e / tensor_f
# 这些都是按照元素进行的运算

(tensor([[1.5686, 0.9374],
         [0.5734, 0.4406]]),
 tensor([[-0.0035,  0.6586],
         [ 0.3708, -0.2779]]),
 tensor([[0.6151, 0.1112],
         [0.0478, 0.0292]]),
 tensor([[0.9955, 5.7243],
         [4.6606, 0.2264]]))

In [37]:
th.exp(tensor_e)

tensor([[2.1870, 2.2210],
        [1.6034, 1.0847]])

In [40]:
# 重要！！！ cat函数
X = th.zeros((3, 4), dtype=th.float32)
Y = th.ones((3, 4), dtype=th.int64)
Z = th.cat((X, Y)) # 默认是按照第一个轴进行拼接
pp(Z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [41]:
th.cat((X, Y), dim=0), th.cat((X, Y), dim=1)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]))

In [45]:
B = 4
N = 8

feat_1 = th.ones((B, N))
feat_2 = th.zeros((B, N))
th.cat((feat_1, feat_2), dim=0), th.cat((feat_1, feat_2), dim=-1)

(tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [46]:
feat_1 == feat_2

tensor([[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False]])

In [48]:
feat_1.sum().item() # item 函数能够将张量中的元素拿出来

32.0

In [53]:
tensor_g = th.arange(12)
for x in tensor_g:
    print(x.item(), end=",")

0,1,2,3,4,5,6,7,8,9,10,11,

In [56]:
tensor_g.itemsize

8

In [57]:
# 广播机制
A = th.arange(3).reshape((3, 1))
B = th.arange(2).reshape((1, 2))
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [58]:
C = A + B

In [59]:
C[-1]

tensor([2, 3])

In [60]:
C[1, 1], C[1][1]

(tensor(2), tensor(2))

In [62]:
C[:, 1]

tensor([1, 2, 3])

In [65]:
import numpy as np

numpy_A = A.numpy()
pp(numpy_A)
pp(A)

array([[0],
       [1],
       [2]])
tensor([[0],
        [1],
        [2]])


In [68]:
H = th.tensor(numpy_A)
H

tensor([[0],
        [1],
        [2]])