In [1]:
import torch

print(torch.__version__) # torch version
print(torch.cuda.is_available()) # Check GPU avaliable
print(torch.cuda.device_count()) # Check GPU count
print(torch.cuda.get_device_name())


2.6.0+cu124
True
1
NVIDIA GeForce RTX 4060 Laptop GPU


In [2]:
x = torch.arange(12) # Here we create a vector of size 12
# [NOTE] 
# th.range will be removed in future versions.
x # x is in CPU

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape # Check the shape of the data

torch.Size([12])

In [4]:
device = torch.device('cuda:0') # Here we can use cpu or cuda or cuda:0
x.to(device)
x.device

device(type='cpu')

In [5]:
x = torch.rand(4, 5) # [4, 5]
x, x.numel() # number of elements

(tensor([[0.3981, 0.1220, 0.7062, 0.9459, 0.5816],
         [0.9165, 0.9984, 0.5471, 0.9907, 0.1345],
         [0.9649, 0.3973, 0.0658, 0.9876, 0.7786],
         [0.0303, 0.4072, 0.1525, 0.5643, 0.5153]]),
 20)

In [6]:
x.size()

torch.Size([4, 5])

In [7]:
x = x.reshape(2, 10)
x

tensor([[0.3981, 0.1220, 0.7062, 0.9459, 0.5816, 0.9165, 0.9984, 0.5471, 0.9907,
         0.1345],
        [0.9649, 0.3973, 0.0658, 0.9876, 0.7786, 0.0303, 0.4072, 0.1525, 0.5643,
         0.5153]])

In [8]:
x = torch.zeros(4, 5)

In [9]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
x = torch.ones(4, 5)
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
x = torch.rand(4, 5)
x

tensor([[0.1073, 0.4250, 0.5539, 0.8125, 0.3835],
        [0.3057, 0.6357, 0.7864, 0.3044, 0.2746],
        [0.0750, 0.6009, 0.7598, 0.1854, 0.8428],
        [0.9807, 0.7324, 0.6249, 0.9252, 0.5657]])

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X.shape, Y.shape, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(torch.Size([3, 4]),
 torch.Size([3, 4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
X.dim()

2

In [16]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
X.sum()

tensor(66.)

In [18]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [21]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [23]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [24]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1793024055136
id(Z): 1793024055136


In [25]:
before = id(X)
X += Y
id(X) == before

True

In [26]:
before = id(X)
X = X + Y
id(X) == before

False

In [27]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a), a.numpy()

(tensor([3.5000]), 3.5, 3.5, 3, array([3.5], dtype=float32))